### ISSUE TITLE
Can't build Starlight in Deno

### ISSUE THREAD

**Issue by JLarky** [withastro/starlight#179]
### What version of `starlight` are you using?

0.1.2

### What version of `astro` are you using?

2.6.1

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

yarn astro add deno && yarn build

<img width="1404" alt="image" src="https://github.com/withastro/starlight/assets/7026/16f3be0d-f412-4da9-98d9-399e0f29cada">

<details>
<summary>error text</summary>

04:15:59 PM [build] Building server entrypoints...
[commonjs--resolver] Cannot bundle Node.js built-in "node:path" imported from "node_modules/@astrojs/starlight/utils/navigation.ts". Consider disabling ssr.noExternal or remove the built-in dependency.
 error   Cannot bundle Node.js built-in "node:path" imported from "node_modules/@astrojs/starlight/utils/navigation.ts". Consider disabling ssr.noExternal or remove the built-in dependency.
RollupError: Cannot bundle Node.js built-in "node:path" imported from "node_modules/@astrojs/starlight/utils/navigation.ts". Consider disabling ssr.noExternal or remove the built-in dependency.
    at error (file:///Users/jlarky/Public/github/JLarky/astro-starlight-tailwind-template/node_modules/rollup/dist/es/shared/node-entry.js:2130:30)
    at Object.error (file:///Users/jlarky/Public/github/JLarky/astro-starlight-tailwind-template/node_modules/rollup/dist/es/shared/node-entry.js:24508:20)
    at Object.resolveId (file:///Users/jlarky/Public/github/JLarky/astro-starlight-tailwind-template/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:22887:34)
    at Object.handler (file:///Users/jlarky/Public/github/JLarky/astro-starlight-tailwind-template/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46681:19)
    at file:///Users/jlarky/Public/github/JLarky/astro-starlight-tailwind-template/node_modules/rollup/dist/es/shared/node-entry.js:24707:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/jlarky/Public/github/JLarky/astro-starlight-tailwind-template/node_modules/rollup/dist/es/shared/node-entry.js:24607:28)
    at async resolveId (file:///Users/jlarky/Public/github/JLarky/astro-starlight-tailwind-template/node_modules/rollup/dist/es/shared/node-entry.js:23451:26)
    at async ModuleLoader.resolveId (file:///Users/jlarky/Public/github/JLarky/astro-starlight-tailwind-template/node_modules/rollup/dist/es/shared/node-entry.js:23715:15)
    at async Object.resolveId (file:///Users/jlarky/Public/github/JLarky/astro-starlight-tailwind-template/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:7990:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/jlarky/Public/github/JLarky/astro-starlight-tailwind-template/node_modules/rollup/dist/es/shared/node-entry.js:24607:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
</details>

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jasikpark** [comment]
would that work if you enable the node compat? https://deno.com/blog/v1.30#support-for-built-in-nodejs-modules

**Comment by delucis** [comment]
Ah, actually, I'm not sure Starlight would support any SSR adapters currently. There are a couple of API edges that made it hard to design for both static and SSR builds and we opted for static-first. SSR support is something we'll target eventually though.

So even if we removed Node APIs Deno doesn't like, the site would still not work as expected.

**Comment by delucis** [comment]
I’m going to close this as  “Works as expected **(for now)**”.

We do want to support SSR eventually, but may take a few months before we have all the tools needed for that.
