### ISSUE TITLE
Can't Build in SSR on Cloudflare

### ISSUE THREAD

**Issue by tsavpyn** [withastro/starlight#1984]
### What version of `starlight` are you using?

0.23.1

### What version of `astro` are you using?

4.9.2

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Edge Chromium

### Describe the Bug

I expected to use Supabase for authentication on my Starlight site, and followed the instruction from [Supabase & Astro | Docs](https://docs.astro.build/en/guides/backend/supabase) in which said that an Astro project with SSR enabled is required. 

I deployed my project to Cloudflare Pages before so certainly I followed the instructions and configured @astrojs/cloudflare for SSR feature correctly. Also I have noticed that node.js is not supported in Cloudflare SSR so I also did the compatible jobs given by both Cloudflare Docs and Astro Docs. 

Unexpected that I still got errors after that, I ran `npm run build` and received errors as below: 
```
[GenerateContentTypesError] `astro sync` command failed to generate content collection types: filename.split is not a function
  Hint:
    Check your `src/content/config.*` file for typos.
  Error reference:
    https://docs.astro.build/en/reference/errors/generate-content-types-error/
  Stack trace:
    at syncContentCollections (file:///C:/Users/makarov/WebstormProjects/rookies/node_modules/astro/dist/core/sync/index.js:110:11)
    at async AstroBuilder.run (file:///C:/Users/makarov/WebstormProjects/rookies/node_modules/astro/dist/core/build/index.js:162:23)
    at async build (file:///C:/Users/makarov/WebstormProjects/rookies/node_modules/astro/dist/cli/build/index.js:20:3)
    at async cli (file:///C:/Users/makarov/WebstormProjects/rookies/node_modules/astro/dist/cli/index.js:168:5)
  Caused by:
  filename.split is not a function
    at normalizePath (file:///C:/Users/makarov/WebstormProjects/rookies/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:2725:21)
    at Object.test (file:///C:/Users/makarov/WebstormProjects/rookies/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:2749:33)
    at file:///C:/Users/makarov/WebstormProjects/rookies/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:49941:34
    at shouldExternalizeForSSR (file:///C:/Users/makarov/WebstormProjects/rookies/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:49879:12)        
    at Array.map (<anonymous>)
``` 

I have no idea how and why. I regard this as a bug that is unexpected to appear. Is Starlight not compatible with SSR mode? 
Or is there any way else that I can use Supabase authentication without enabling SSR mode? 

Really appreciate it if this could be solved. 

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/starlight/tree/main/examples/basics?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
I think this might be a bug in the Cloudflare adapter rather than Starlight but not 100% sure. 

Are you able to share a reproduction? The URL you included in the issue links to our default starter template, which doesn't use the Cloudflare adapter.

**Comment by tsavpyn** [comment]
Sure! Apologize for forgetting putting my production into the template. Here is the link to the reproduction:

[Starlight Issue #1984 Reproduction on Stackblitz](https://stackblitz.com/edit/github-9bvnkb)

I hope this helps. Many thanks for answering.

**Comment by delucis** [comment]
Thank you for the reproduction! I’m going to move this over to our adapters repo as I’m guessing this may need digging from the people who know how those work.
