### ISSUE TITLE
On entreprise proxy i cannot bootstrap starlight but i can with astro UND_ERR_CONNECT_TIMEOUT'

### ISSUE THREAD

**Issue by yodatak** [withastro/starlight#2241]
### What version of `starlight` are you using?

latest

### What version of `astro` are you using?

latest

### What package manager are you using?

pnpm

### What operating system are you using?

Linux WSL2

### What browser are you using?

Edge

### Describe the Bug

When i run this command

NODE_DEBUG=net pnpm create astro --template starlight

```

NET 102801: _read - n 16384 isConnecting? false hasHandle? true
NET 102801: Socket._handle.readStart
NET 102801: _read - n 16384 isConnecting? false hasHandle? true
NET 102801: Socket._handle.readStart
NET 102801: _read - n 16384 isConnecting? false hasHandle? true
NET 102801: Socket._handle.readStart
NET 102801: _read - n 16384 isConnecting? false hasHandle? true
NET 102801: Socket._handle.readStart
NET 102801: _final: not ended, call shutdown()
NET 102801: afterShutdown destroyed=false
NET 102801: destroy
NET 102801: close
NET 102801: close handle
NET 102801: _final: not ended, call shutdown()
NET 102801: afterShutdown destroyed=false
NET 102801: destroy
NET 102801: close
NET 102801: close handle
NET 102801: destroy
NET 102801: close
NET 102801: close handle
NET 102801: emit close
NET 102801: emit close
NET 102801: emit close
NET 102801: _read - n 16384 isConnecting? false hasHandle? true
NET 102801: Socket._handle.readStart
NET 102801: _read - n 16384 isConnecting? false hasHandle? true
NET 102801: Socket._handle.readStart
NET 102801: pipe false undefined
NET 102801: connect: find host api.github.com
NET 102801: connect: dns options { family: undefined, hints: 32 }
NET 102801: connect: autodetecting
NET 102801: _read - n 16384 isConnecting? true hasHandle? true
NET 102801: _read wait for connection
NET 102801: _read - n 16384 isConnecting? false hasHandle? true
NET 102801: _final: not ended, call shutdown()
NET 102801: afterShutdown destroyed=false
NET 102801: destroy
NET 102801: close
NET 102801: close handle
NET 102801: _final: not ended, call shutdown()
NET 102801: afterShutdown destroyed=false
NET 102801: destroy
NET 102801: close
NET 102801: close handle
NET 102801: destroy
NET 102801: close
NET 102801: close handle
NET 102801: emit close
NET 102801: emit close
NET 102801: emit close
NET 102801: connect/multiple: only one address found, switching back to single connection
NET 102801: connect: attempting to connect to 140.82.121.5:443 (addressType: 4)
NET 102801: _read - n 16384 isConnecting? false hasHandle? true
NET 102801: _final: not ended, call shutdown()
NET 102801: destroy
NET 102801: close
NET 102801: close handle
NET 102801: _final: not ended, call shutdown()
NET 102801: destroy
NET 102801: close
NET 102801: close handle
NET 102801: afterShutdown destroyed=true
NET 102801: emit close
NET 102801: afterShutdown destroyed=true
NET 102801: emit close
NET 102801: destroy
NET 102801: close
NET 102801: close handle
NET 102801: pipe false undefined
NET 102801: connect: find host XXXXX
NET 102801: connect: dns options { family: undefined, hints: 32 }
NET 102801: connect: autodetecting
NET 102801: _read - n 16384 isConnecting? true hasHandle? true
NET 102801: _read wait for connection
NET 102801: emit close
NET 102801: connect/multiple: only one address found, switching back to single connection
NET 102801: connect: attempting to connect to XXXXX:443 (addressType: 4)
NET 102801: afterConnect
NET 102801: _read - n 16384 isConnecting? false hasHandle? true
NET 102801: Socket._handle.readStart
NET 102801: _read - n 16384 isConnecting? false hasHandle? true
NET 102801: _read - n 16384 isConnecting? false hasHandle? true
NET 102801: _read - n 16384 isConnecting? false hasHandle? true
NET 102801: destroy
NET 102801: close
NET 102801: close handle
NET 102801: emit close
NET 102801: destroy
NET 102801: close
NET 102801: close handle
/usr/lib/node_modules_20/undici/index-fetch.js:8
      Error.captureStackTrace(err, this)
            ^

TypeError: fetch failed
    at /usr/lib/node_modules_20/undici/index-fetch.js:8:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async verifyTemplate (file:///home/yodatak/.cache/pnpm/dlx/k4qflzyudng66x3e62wclgobkq/1916b0fd564-17944/node_modules/.pnpm/create-astro@4.8.3/node_modules/create-astro/dist/index.js:1221:13)
    at async verify (file:///home/yodatak/.cache/pnpm/dlx/k4qflzyudng66x3e62wclgobkq/1916b0fd564-17944/node_modules/.pnpm/create-astro@4.8.3/node_modules/create-astro/dist/index.js:1201:16)
    at async main (file:///home/yodatak/.cache/pnpm/dlx/k4qflzyudng66x3e62wclgobkq/1916b0fd564-17944/node_modules/.pnpm/create-astro@4.8.3/node_modules/create-astro/dist/index.js:1266:5) {
  [cause]: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (/usr/lib/node_modules_20/undici/lib/core/connect.js:190:24)
      at /usr/lib/node_modules_20/undici/lib/core/connect.js:133:46
      at Immediate._onImmediate (/usr/lib/node_modules_20/undici/lib/core/connect.js:174:9)
      at process.processImmediate (node:internal/timers:478:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

Node.js v20.12.2
``` 

with HTTPS_PROXY=http://XXXX/
HTTP_PROXY=http://XXXXX/
http_proxy=http://XXXX

I think its linked to api.github.com that is block by the proxy how could i do this command without this url or using a different url ?

### Link to Minimal Reproducible Example

cannot because of entreprise issue i think

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lorenzolewis** [comment]
Hi there! The create Astro command will pull the starlight templates from here: https://github.com/withastro/starlight/tree/main/examples

You can choose whichever one you would like to use. 

The other option is to follow the manual setup instructions: https://starlight.astro.build/manual-setup/

**Comment by delucis** [comment]
I’m not sure `create astro` supports pulling templates from non-GitHub locations, so not sure there is much Starlight can do here. (This would likely be a feature request for the [`create astro` package](https://github.com/withastro/astro/tree/main/packages/create-astro).)

As Lorenzo mentioned we do have that manual setup guide. Another option would be to copy/paste the relevant directory from https://github.com/withastro/starlight/tree/main/examples?rgh-link-date=2024-08-19T15%3A32%3A23Z if you were able to clone the Starlight repository. `create astro` doesn’t do _that_ much more, so just grabbing the directory and running `npm install` should work more or less the same.
