### ISSUE TITLE
favicon expects a relative url but treats it as a filename

### ISSUE THREAD

**Issue by techfg** [withastro/starlight#2639]
### What version of `starlight` are you using?

0.29.2

### What version of `astro` are you using?

4.16.10

### What package manager are you using?

npm

### What operating system are you using?

linux

### What browser are you using?

chrome

### Describe the Bug

The [favicon](https://github.com/withastro/starlight/blob/dc481aea7990e06dc6fa980d15ee02db2c67b0a0/packages/starlight/schemas/favicon.ts#L16) configuration parameter expects a relative URL pointing to the favicon.  However, the configuration validation treats the value as a [file path](https://github.com/withastro/starlight/blob/dc481aea7990e06dc6fa980d15ee02db2c67b0a0/packages/starlight/schemas/favicon.ts#L18) in order to detect the file type.

The current approach causes issues when the relative url ends with anything beyond the file extension - for example, when a primitive cache busting approach is applied:

```ts
  integrations: [
    starlight({
      favicon: '/favicon.svg?v=1732649058923',
```

```bash
❯ npm run dev

> @example/starlight-basics@0.0.1 dev
> astro dev

[AstroUserError] Invalid config passed to starlight integration
  Hint:
    favicon must be a .ico, .gif, .jpg, .png, or .svg file
  Location:
    /home/projects/withastro-starlight-qjpiye/node_modules/astro/dist/core/errors/errors.js:120:5
  Stack trace:
    at new AstroUserError (file:///home/projects/withastro-starlight-qjpiye/node_modules/astro/dist/core/errors/errors.js:120:5)
    at Module.parseWithFriendlyErrors (/home/projects/withastro-starlight-qjpiye/node_modules/@astrojs/starlight/utils/error-map.ts:6:10)
    at astro:config:setup (/home/projects/withastro-starlight-qjpiye/node_modules/@astrojs/starlight/index.ts:45:59)
    at async Module.createContainer (file:///home/projects/withastro-starlight-qjpiye/node_modules/astro/dist/core/dev/container.js:39:14)
    at async Module.dev (file:///home/projects/withastro-starlight-qjpiye/node_modules/astro/dist/core/dev/dev.js:40:19)
```

The value for favicon should be parsed as a relative url and the type extracted based on the path and not the entire configuration value.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-starlight-qjpiye?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by techfg** [comment]
Thanks @delucis.  Happy to work on a PR within the next week or so.
