### ISSUE TITLE
Breaks after Astro updates to 5.0.3

### ISSUE THREAD

**Issue by Signum** [withastro/starlight#2658]
### What version of `starlight` are you using?

0.29.2

### What version of `astro` are you using?

5.0.3

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

Astro asked me to update to version 5. So I did:

```
pnpm dlx @astrojs/upgrade

 astro   Integration upgrade in progress.

      ◼  @astrojs/check is up to date on v0.9.4
      ◼  @astrojs/sitemap is up to date on v3.2.1
      ●  @astrojs/starlight will be updated to v0.29.2
      ▲  astro will be updated to  v5.0.3 

  wait   One package has breaking changes. Continue?
         Yes

 check   Be sure to follow the CHANGELOG.
         astro Upgrade to Astro v5

 ██████  Installing dependencies with pnpm...

╭─────╮  Houston:
│ ◠ ◡ ◠  Have fun building!
╰─────╯
```

…which I immediately regretted…

```
npx astro dev            
16:58:46 [vite] (ssr) Error when evaluating SSR module /home/chaas/projekte/ispmail-astro/workaround/astro.config.mjs:
|- Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './jsx/renderer.js' is not defined by "exports" in /home/chaas/projekte/ispmail-astro/workaround/node_modules/.pnpm/@astrojs+mdx@3.1.8_astro@5.0.3_rollup@4.24.0_typescript@5.6.3_yaml@2.6.0_/node_modules/astro/package.json imported from /home/chaas/projekte/ispmail-astro/workaround/node_modules/.pnpm/@astrojs+mdx@3.1.8_astro@5.0.3_rollup@4.24.0_typescript@5.6.3_yaml@2.6.0_/node_modules/@astrojs/mdx/dist/index.js
    at exportsNotFound (node:internal/modules/esm/resolve:314:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:662:9)
    at packageResolve (node:internal/modules/esm/resolve:842:14)
    at moduleResolve (node:internal/modules/esm/resolve:926:18)
    at defaultResolve (node:internal/modules/esm/resolve:1056:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:654:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:603:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:586:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:242:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:135:49)

[astro] Unable to load your Astro config

Package subpath './jsx/renderer.js' is not defined by "exports" in /home/chaas/projekte/ispmail-astro/workaround/node_modules/.pnpm/@astrojs+mdx@3.1.8_astro@5.0.3_rollup@4.24.0_typescript@5.6.3_yaml@2.6.0_/node_modules/astro/package.json imported from /home/chaas/projekte/ispmail-astro/workaround/node_modules/.pnpm/@astrojs+mdx@3.1.8_astro@5.0.3_rollup@4.24.0_typescript@5.6.3_yaml@2.6.0_/node_modules/@astrojs/mdx/dist/index.js
  Stack trace:
    at exportsNotFound (node:internal/modules/esm/resolve:314:10)
    at packageResolve (node:internal/modules/esm/resolve:842:14)
    at defaultResolve (node:internal/modules/esm/resolve:1056:11)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:603:25)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:242:38)
```

### Link to Minimal Reproducible Example

https://github.com/Signum/starlight-astro5-breakage

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by logaretm** [comment]
Seeing this as well after upgrade to v5 👍

**Comment by morellodev** [comment]
As a temporary fix, add this to your `package.json`:

```json
"overrides": {
  "@astrojs/mdx": "^4.0.0"
}
```

**Comment by samr11th** [comment]
@morellodev added the override, but still got the same issue

**Comment by samrith-s** [comment]
@morellodev added the override, but still got the same issue

**Comment by morellodev** [comment]
Did you re-run `npm install` again? Which package manager are you using?

**Comment by PandaLord** [comment]
same here, and i am using pnpm for now

**Comment by morellodev** [comment]
The work around is fine for me, if you use `pnpm` you need to edit the `package.json` as follows (reference [here](https://pnpm.io/package_json#pnpmoverrides)):

```json
"pnpm": {
  "overrides": {
    "@astrojs/mdx": "^4.0.0"
  }
}
```

and then re-run `pnpm install`. This should fix the issue!

**Comment by PandaLord** [comment]
Thanks @morellodev , after removing the node_modules and use your configuration, works fine now. Thanks!

**Comment by samr11th** [comment]
@morellodev I am using Yarn

**Comment by samrith-s** [comment]
@morellodev I am using Yarn

**Comment by DavidJFelix** [comment]
> ```json
> "pnpm": {
>   "overrides": {
>     "@astrojs/mdx": "^4.0.0"
>   }
> }
> ```

@samrith-s I think you can use resolutions: https://yarnpkg.com/configuration/manifest#resolutions

**Comment by samrith-s** [comment]
> > ```json
> 
> > "pnpm": {
> 
> >   "overrides": {
> 
> >     "@astrojs/mdx": "^4.0.0"
> 
> >   }
> 
> > }
> 
> > ```
> 
> 
> 
> @samrith-s I think you can use resolutions: https://yarnpkg.com/configuration/manifest#resolutions 

@DavidJFelix tried doing that, but still got the same error unfortunately

**Comment by Smart-Ace-Designs** [comment]
For bun, this worked for me:

```
"overrides": {
  "@astrojs/mdx": "^4.0.0"
}
```

And had to add this to `astro.config.mjs`:

```
legacy: {
    collections: true,
  },
```

Delete node_modules and then `bun i`

**Comment by HiDeoo** [comment]
Support for Astro v5 has been released in Starlight [`v0.30.0`](https://github.com/withastro/starlight/releases/tag/%40astrojs%2Fstarlight%400.30.0). Thanks for your patience.

**Comment by andersk** [comment]
Something’s still broken. If you open the [official StackBlitz template](https://stackblitz.com/github/withastro/starlight/tree/main/examples/basics) linked from [getting started](https://starlight.astro.build/getting-started/), it uses astro 5.0.8 and @astrojs/starlight 0.30.2, but it shows an error page and the following console output:

```
❯ npm install && npm run dev

added 417 packages in 11s

206 packages are looking for funding
  run `npm fund` for details

> @example/starlight-basics@0.0.1 dev
> astro dev

14:00:37 [types] Generated 4ms

 astro  v5.0.8 ready in 7137 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

The collection "docs" does not exist or is empty. Ensure a collection directory with this name exists.
14:00:41 [content] Syncing content
14:00:41 [content] Content config changed
14:00:41 [content] Astro version changed
14:00:41 [content] Clearing content store
14:00:41 [content] Synced content
14:00:41 watching for file changes...
14:00:46 [ERROR] [RenderUndefinedEntryError] 
  Hint:
    Check if the entry is undefined before passing it to `render()`
  Error reference:
    https://docs.astro.build/en/reference/errors/render-undefined-entry-error/
  Stack trace:
    at /home/projects/yqnimzjvjx.github/node_modules/astro/dist/core/errors/errors.js:13:5
    [...] See full stack trace in the browser, or rerun with --verbose.
```

**Comment by delucis** [comment]
> Something’s still broken. If you open the [official StackBlitz template](https://stackblitz.com/github/withastro/starlight/tree/main/examples/basics) linked from [getting started](https://starlight.astro.build/getting-started/), it uses astro 5.0.8 and @astrojs/starlight 0.30.2, but it shows an error page and the following console output:

Astro seems to be struggling with race conditions around content collections in v5. If you manually run `astro sync` before `astro dev`, things seems to work OK. Hoping we can find a solution soon.

**Comment by samrith-s** [comment]
Starlight with `@astrojs/starlight-tailwind` still breaks with the same error.

```
13:31:44 [vite] (ssr) Error when evaluating SSR module ~/Projects/hali/docs/astro.config.ts:
|- Error: Cannot find module '~/Projects/hali/docs/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1181:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1169:15)
    at resolveExports (node:internal/modules/cjs/loader:591:14)
    at Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (~/Projects/hali/docs/node_modules/sucrase/dist/computeSourceMap.js:1:92)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)

[astro] Unable to load your Astro config

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Cannot find module '~/Work/Projects/hali/docs/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1181:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1169:15)
    at resolveExports (node:internal/modules/cjs/loader:591:14)
    at Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (~/Projects/hali/docs/node_modules/sucrase/dist/computeSourceMap.js:1:92)
    at Module._compile (node:internal/modules/cjs/loader:1376:14) {
  code: 'MODULE_NOT_FOUND',
  path: '~/Work/Projects/hali/docs/node_modules/@jridgewell/gen-mapping/package.json'
}

Node.js v20.11.1
```

**Comment by delucis** [comment]
> Starlight with `@astrojs/starlight-tailwind` still breaks with the same error.
