### ISSUE TITLE
Brand new starlight project will not build

### ISSUE THREAD

**Issue by pierskarsenbarg** [withastro/starlight#2734]
### What version of `starlight` are you using?

0.30.3

### What version of `astro` are you using?

5.1.0

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Brand new installation of starlight: `npm create astro@latest -- --template starlight`

Ran `npm run build` and received the following error:

```
[ERROR] [vite] x Build failed in 190ms
Expected identifier but found "import"
  Location:
    (define name):1:0
  Stack trace:
    at failureErrorWithLog (/Users/piers/go/src/github.com/pierskarsenbarg/astro-starlight-docker/node_modules/vite/node_modules/esbuild/lib/main.js:1476:15)
    at responseCallbacks.<computed> (/Users/piers/go/src/github.com/pierskarsenbarg/astro-starlight-docker/node_modules/vite/node_modules/esbuild/lib/main.js:622:9)
    at Socket.readFromStdout (/Users/piers/go/src/github.com/pierskarsenbarg/astro-starlight-docker/node_modules/vite/node_modules/esbuild/lib/main.js:600:7)
    at addChunk (node:internal/streams/readable:559:12)
    at Readable.push (node:internal/streams/readable:390:5)
```

### Link to Minimal Reproducible Example

https://github.com/pierskarsenbarg/astro-starlight-shiki-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for the report.

Turns out this is also related to the same issue as https://github.com/withastro/starlight/issues/2733 and Astro is actively working on fixing it.

You can follow the progress in https://github.com/withastro/astro/issues/12796.

You definitely started a brand new project at a bad timing with this upstream issue. Sorry for the inconvenience.
